changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Firmware
      labels:
        - firmware
        - embedded
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Bugs Fixed
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - maintenance
        - dependencies
    - title: Other Changes
      labels:
        - "*"
