# Any extra libraries included by this sketch (space separated)
LIBRARIES = dcs-bios-arduino-library Wire ArduinoJoystickLibrary Joystick_ESP32S2 openhornet-mt6835-library

# Uncomment one of the following to choose the target board
# include $(ROOTDIR)/include/mega2560.mk
# include $(ROOTDIR)/include/promicro.mk
# include $(ROOTDIR)/include/promini.mk
include $(ROOTDIR)/include/s2mini.mk
