# Any extra libraries included by this sketch (space separated)
LIBRARIES = Adafruit_NeoPixel Servo dcs-bios-arduino-library TCA9534 Wire ArduinoJoystickLibrary Stepper Joystick_ESP32S2 Arduino-FOC Arduino-FOC-drivers

# Uncomment one of the following to choose the target board
# include $(ROOTDIR)/include/mega2560.mk
# include $(ROOTDIR)/include/promicro.mk
# include $(ROOTDIR)/include/promini.mk
include $(ROOTDIR)/include/s2mini.mk
