# Any extra libraries included by this sketch (space separated)
LIBRARIES = SPI ArduinoJoystickLibrary EEPROM

# Uncomment one of the following to choose the target board
# include $(ROOTDIR)/include/mega2560.mk
include $(ROOTDIR)/include/promicro.mk
# include $(ROOTDIR)/include/promini.mk
# include $(ROOTDIR)/include/s2mini.mk
