name=MT6835 Encoder Library
author=Sandra Carroll(sandra)
maintainer=Sandra Carroll(sandra)
sentence=MT6935 Magnetic Encoder Libary for Openhornet
paragraph=
url=https://github.com/
category=Driver
version=0.6.1
