API Documentation: Board Class Reference
Board Class Reference
Public Member Functions
void setupRotaryEncoder (int encSwPin, int encAPin, int encBPin)
Sets up the rotary encoder with switch and encoder pins.
void registerChannel (Channel *channel)
Registers a channel with the board.
void updateLeds ()
Update the physical LED state.
int handleModeChange ()
Handles mode change button press and returns current mode.
void processMode ()
Processes the current mode.
void fillSolid (const CRGB &color, int brightness=-1)
Fills all channels with a solid color.
void setAllLightsOff ()
Turns off all lights in all channels and resets brightness state.
void updateInstrumentLights (uint16_t newValue)
Updates all channels with new instrument lighting value.
void updateConsoleLights (uint16_t newValue)
Updates all channels with new console lighting value.
void updateFloodLights (uint16_t newValue)
Updates all channels with new flood lighting value.
Static Public Member Functions
static Board * getInstance ()
Gets or createsthe singleton instance of the Board class.
static void onInstrIntLtChange (unsigned int newValue)
Callback for instrument lighting changes from DCS-BIOS.
static void onConsolesDimmerChange (unsigned int newValue)
Callback for console dimmer changes from DCS-BIOS.
static void onFloodDimmerChange (unsigned int newValue)
Callback for flood lighting changes from DCS-BIOS.
Public Attributes
DcsBios::IntegerBuffer instrIntLtBuffer {FA_18C_hornet_INSTR_INT_LT, onInstrIntLtChange}
DcsBios::IntegerBuffer consolesDimmerBuffer {FA_18C_hornet_CONSOLES_DIMMER, onConsolesDimmerChange}
DcsBios::IntegerBuffer floodDimmerBuffer {FA_18C_hornet_FLOOD_DIMMER, onFloodDimmerChange}
Detailed Description
Definition at line 45 of file Board.h.
Member Function Documentation
getInstance()
static Board * Board::getInstance () inline static
Gets or createsthe singleton instance of the Board class.
See also
This method is called by setup() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 96 of file Board.h.
{
        return instance ? instance : (instance = new Board()); }
setupRotaryEncoder()
void Board::setupRotaryEncoder (int encSwPin, int encAPin, int encBPin) inline
Sets up the rotary encoder with switch and encoder pins.
Parameters
encSwPin Pin number for the encoder switch
encAPin Pin number for encoder A
encBPin Pin number for encoder B
See also
This method is called by setup() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 106 of file Board.h.
{
        this->encSwPin = encSwPin;
        pinMode(encSwPin, INPUT_PULLUP);                              // Initialize mode change pin
        encoder = new RotaryEncoder(encAPin, encBPin, RotaryEncoder::LatchMode::TWO03);
    }
registerChannel()
void Board::registerChannel (Channel * channel) inline
Registers a channel with the board.
Parameters
channel Pointer to the channel to register
See also
This method is called by setup() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 117 of file Board.h.
{
        channels[channelCount++] = channel;
    }
updateLeds()
void Board::updateLeds () inline
Update the physical LED state.
See also
This method is called by loop() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 125 of file Board.h.
                      {
        if (LedUpdateState::getInstance()->getUpdateFlag()) {
            updCountdown = (updCountdown == 0) ? 32 : updCountdown;   // Countdown logic allows to collect LED updates
            updCountdown--;                                           // from 32 loop() calls into one FastLED.show()
            if (updCountdown == 0) {                                  // Trigger FastLED.show() at end of countdown
                cli();
                FastLED.show();
                LedUpdateState::getInstance()->setUpdateFlag(false);  // Reset update flag
                sei();
            }
        }
    }
References LedUpdateState::getInstance(), and LedUpdateState::setUpdateFlag().
handleModeChange()
int Board::handleModeChange () inline
Handles mode change button press and returns current mode.
Returns
The current mode after handling the button press
See also
This method is called by loop() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 144 of file Board.h.
{
        static bool lastButtonState = HIGH;
        static unsigned long lastButtonPressTime = 0;
        const unsigned long BUTTON_WAIT = 1000;                       // Wait time in milliseconds between button presses
        bool currentButtonState = digitalRead(encSwPin);              // Read the state of the encoder switch
        unsigned long currentTime = millis();                          // Get current time in milliseconds
        if (currentButtonState == LOW && lastButtonState == HIGH) {   // Button has just been pressed
            if (currentTime - lastButtonPressTime < BUTTON_WAIT) {    // Only process if 1 sec passed since last press
                lastButtonState = currentButtonState;
                return currentMode;
            }
            lastButtonPressTime = currentTime;                        // Update last press time
            int previousMode = currentMode;                           // Store previous mode
            currentMode = (currentMode % 3) + 1;                      // Cycle to next mode
            if (currentMode == MODE_NORMAL) {
                setAllLightsOff();
                sendDcsBiosMessage("CONSOLES_DIMMER", String(dcs_brightness_console).c_str());           // Send DCS-BIOS message to reset console dimmer
                sendDcsBiosMessage("INST_PNL_DIMMER", String(dcs_brightness_instrument).c_str());        // Send DCS-BIOS message to reset instrument lighting
                sendDcsBiosMessage("FLOOD_DIMMER", String(dcs_brightness_flood).c_str());                  // Send DCS-BIOS message to reset floodlights dimmer
            }
            if (currentMode == MODE_MANUAL) {
                mode2_brightness = 64;                                // Reset to 25% brightness
                fillSolid(NVIS_GREEN_A);                              // Apply the brightness immediately
            }
            if (currentMode == MODE_RAINBOW) {
                mode3_brightness = 64;                                // Reset to 25% brightness
                encoder->tick();                                      // Update encoder state
                rotary_pos = encoder->getPosition();                  // Sync encoder position to avoid false change detection
                setAllLightsOff();                                    // Clear any previous state
            }
            lastButtonState = currentButtonState;
            delay(10);                                                // Small delay to debounce switch
        } else {
            lastButtonState = currentButtonState;
        }
        return currentMode;
    }
References fillSolid(), and setAllLightsOff().
processMode()
void Board::processMode () inline
Processes the current mode.
See also
This method is called by loop() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 190 of file Board.h.
                       {
        int newPos = 0;
        switch(currentMode) {
            case MODE_NORMAL:                                         // MODE 1: LEDs controlled by DCS BIOS
                {
                    DcsState currentDcsState = getDcsState();
                    if (currentDcsState == DcsState::EXITED && prevDcsState != DcsState::EXITED) {
                        setAllLightsOff();                            // DCS just exited: turn off all lights
                    } else if (prevDcsState == DcsState::EXITED &&
                               currentDcsState != DcsState::EXITED &&
                               currentDcsState != DcsState::PAUSED) {
                        for (int i = 0; i < channelCount; i++) {     // DCS became active again: restore last known brightness
                            channels[i]->updateInstrLights(dcs_brightness_instrument);
                            channels[i]->updateConsoleLights(dcs_brightness_console);
                            channels[i]->updateFloodLights(dcs_brightness_flood);
                        }
                        LedUpdateState::getInstance()->setUpdateFlag(true);
                    }
                    // PAUSED: do nothing - keep current light state
                    prevDcsState = currentDcsState;
                    DcsBios::loop();
                }
                break;
            case MODE_MANUAL:                                         // MODE 2: LEDs controlled manually through BKLT switch
                encoder->tick();
                newPos = encoder->getPosition();
                if (newPos != rotary_pos) {
                    RotaryEncoder::Direction direction = encoder->getDirection();
                    if (direction == RotaryEncoder::Direction::CLOCKWISE) {
                        mode2_brightness = (mode2_brightness < 224) ? mode2_brightness + 32 : 255;  // Add 32 or cap at 255
                    } else {
                        mode2_brightness = (mode2_brightness > 32) ? mode2_brightness - 32 : 0;  // Subtract 32 or cap at 0
                    }
                    rotary_pos = newPos;
                    fillSolid(NVIS_GREEN_A);
                }
                break;
            case MODE_RAINBOW:                                        // MODE 3: Rainbow test mode
                encoder->tick();
                newPos = encoder->getPosition();
                if (newPos != rotary_pos) {
                    RotaryEncoder::Direction direction = encoder->getDirection();
                    if (direction == RotaryEncoder::Direction::CLOCKWISE) {
                        mode3_brightness = (mode3_brightness < 224) ? mode3_brightness + 32 : 255;  // Add 32 or cap at 255
                    } else {
                        mode3_brightness = (mode3_brightness > 32) ? mode3_brightness - 32 : 0;  // Subtract 32 or cap at 0
                    }
                    rotary_pos = newPos;
                }
                for (int i = 0; i < channelCount; i++) {
                    fill_rainbow(channels[i]->getLeds(), channels[i]->getLedCount(), thisHue, deltaHue);
                    // Scale down brightness to reduce maximum brightness
                    nscale8_video(channels[i]->getLeds(), channels[i]->getLedCount(), mode3_brightness);
                }
                thisHue++;  // Increment the hue for the next frame
                LedUpdateState::getInstance()->setUpdateFlag(true);
                break;
        }
    }
References fillSolid(), getDcsState(), LedUpdateState::getInstance(), setAllLightsOff(), LedUpdateState::setUpdateFlag(), Channel::updateConsoleLights(), Channel::updateFloodLights(), and Channel::updateInstrLights().
fillSolid()
void Board::fillSolid (const CRGB & color, int brightness = -1) inline
Fills all channels with a solid color.
Parameters
color The color to fill with
brightness Optional brightness value (0-255). If not provided, uses current brightness
See also
This method is called by handleModeChange() and processMode() in Board.h, conditionally in MODE_MANUAL case
Definition at line 257 of file Board.h.
                                                           {          // Fill all channels with a solid color
        int targetBrightness = (brightness >= 0) ? brightness : this->mode2_brightness;
        for (int i = 0; i < channelCount; i++) {
            channels[i]->updateInstrLights(map(targetBrightness, 0, 255, 0, 65535), color);
            channels[i]->updateConsoleLights(map(targetBrightness, 0, 255, 0, 65535), color);
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);
    }
References LedUpdateState::getInstance(), LedUpdateState::setUpdateFlag(), Channel::updateConsoleLights(), and Channel::updateInstrLights().
Referenced by handleModeChange(), and processMode().
setAllLightsOff()
void Board::setAllLightsOff () inline
Turns off all lights in all channels and resets brightness state.
See also
This method is called by handleModeChange() in Board.h
Definition at line 270 of file Board.h.
                           {                                         // Turn off all lights and reset brightness state
        for (int i = 0; i < channelCount; i++) {
            channels[i]->setAllLightsOff();
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);
    }
References LedUpdateState::getInstance(), Channel::setAllLightsOff(), and LedUpdateState::setUpdateFlag().
Referenced by handleModeChange(), and processMode().
updateInstrumentLights()
void Board::updateInstrumentLights (uint16_t newValue) inline
Updates all channels with new instrument lighting value.
Parameters
newValue The new brightness value
See also
This method is conditionally called by onInstrIntLtChange() in Board.h
Definition at line 282 of file Board.h.
{
        dcs_brightness_instrument = newValue;                         // In any mode, store the DCS-BIOS brightness value
        if (currentMode != MODE_NORMAL) return;                       // But only in normal mode, actually send update to channels
        for (int i = 0; i < channelCount; i++) {
            channels[i]->updateInstrLights(newValue);
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);
    }
References LedUpdateState::getInstance(), LedUpdateState::setUpdateFlag(), and Channel::updateInstrLights().
Referenced by onInstrIntLtChange().
updateConsoleLights()
void Board::updateConsoleLights (uint16_t newValue) inline
Updates all channels with new console lighting value.
Parameters
newValue The new brightness value
See also
This method is called by onConsolesDimmerChange() in Board.h
Definition at line 297 of file Board.h.
{
        dcs_brightness_console = newValue;                            // In any mode, store the DCS-BIOS brightness value
        if (currentMode != MODE_NORMAL) return;                       // But only in normal mode, actually send update to channels
        for (int i = 0; i < channelCount; i++) {
            channels[i]->updateConsoleLights(newValue);
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);
    }
References LedUpdateState::getInstance(), LedUpdateState::setUpdateFlag(), and Channel::updateConsoleLights().
Referenced by onConsolesDimmerChange().
updateFloodLights()
void Board::updateFloodLights (uint16_t newValue) inline
Updates all channels with new flood lighting value.
Parameters
newValue The new brightness value
See also
This method is called by onFloodDimmerChange() in Board.h
Definition at line 312 of file Board.h.
{
        dcs_brightness_flood = newValue;                              // In any mode, store the DCS-BIOS brightness value
        if (currentMode != MODE_NORMAL) return;                       // But only in normal mode, actually send update to channels
        for (int i = 0; i < channelCount; i++) {
            channels[i]->updateFloodLights(newValue);
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);
    }
References LedUpdateState::getInstance(), LedUpdateState::setUpdateFlag(), and Channel::updateFloodLights().
Referenced by onFloodDimmerChange().
onInstrIntLtChange()
static void Board::onInstrIntLtChange (unsigned int newValue) inline static
Callback for instrument lighting changes from DCS-BIOS.
Parameters
newValue The new brightness value from DCS-BIOS
See also
This method is called by DCS-BIOS when instrument lighting changes
Definition at line 328 of file Board.h.
{
        if (instance) instance->updateInstrumentLights(newValue);
    }
References updateInstrumentLights().
onConsolesDimmerChange()
static void Board::onConsolesDimmerChange (unsigned int newValue) inline static
Callback for console dimmer changes from DCS-BIOS.
Parameters
newValue The new brightness value from DCS-BIOS
See also
This method is called by DCS-BIOS when console dimmer changes
Definition at line 338 of file Board.h.
{
        if (instance) instance->updateConsoleLights(newValue);
    }
References updateConsoleLights().
onFloodDimmerChange()
static void Board::onFloodDimmerChange (unsigned int newValue) inline static
Callback for flood lighting changes from DCS-BIOS.
Parameters
newValue The new brightness value from DCS-BIOS
See also
This method is called by DCS-BIOS when flood lighting changes
Definition at line 348 of file Board.h.
{
        if (instance) instance->updateFloodLights(newValue);
    }
References updateFloodLights().
Member Data Documentation
instrIntLtBuffer
DcsBios::IntegerBuffer Board::instrIntLtBuffer {FA_18C_hornet_INSTR_INT_LT, onInstrIntLtChange}
Definition at line 331 of file Board.h.
{FA_18C_hornet_INSTR_INT_LT, onInstrIntLtChange};
consolesDimmerBuffer
DcsBios::IntegerBuffer Board::consolesDimmerBuffer {FA_18C_hornet_CONSOLES_DIMMER, onConsolesDimmerChange}
Definition at line 341 of file Board.h.
{FA_18C_hornet_CONSOLES_DIMMER, onConsolesDimmerChange};
floodDimmerBuffer
DcsBios::IntegerBuffer Board::floodDimmerBuffer {FA_18C_hornet_FLOOD_DIMMER, onFloodDimmerChange}
Definition at line 351 of file Board.h.
{FA_18C_hornet_FLOOD_DIMMER, onFloodDimmerChange};
The documentation for this class was generated from the following file:
/github/workspace/embedded/OH2_Lower_Instrument_Panel/2A13-BACKLIGHT_CONTROLLER/helpers/Board.h