; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin_s2_mini

[env:lolin_s2_mini]
platform = espressif32@7.0.0
board = lolin_s2_mini
framework = arduino
monitor_port = COM7
monitor_speed = 250000
monitor_echo = yes
build_flags =
;   -D ELOG_SD_ENABLE
;   -D ELOG_SPIFFS_ENABLE
    -D ELOG_SYSLOG_ENABLE
    -D ELOG_TIMER_ENABLE
lib_deps = 
	adafruit/Adafruit TCA8418
	hideakitai/PCA95x5
	fastled/FastLED
	maxint-rd/TM16xx LEDs and Buttons
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ADS1X15
	x385832/Elog@^2.0.17

[env:lolin_s2_mini_debug]
platform = espressif32@7.0.0
board = lolin_s2_mini
framework = arduino
monitor_port = COM7
monitor_speed = 250000
monitor_echo = yes
debug_tool = esp-prog
build_flags =
;   -D ELOG_SD_ENABLE
;   -D ELOG_SPIFFS_ENABLE
    -D ELOG_SYSLOG_ENABLE
    -D ELOG_TIMER_ENABLE
lib_deps = 
	adafruit/Adafruit TCA8418
	hideakitai/PCA95x5
	fastled/FastLED
	maxint-rd/TM16xx LEDs and Buttons
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ADS1X15
	x385832/Elog@^2.0.17

[env:lolin_s3_mini]
platform = espressif32@7.0.0
board = lolin_s2_mini
framework = arduino
monitor_port = COM7
monitor_speed = 250000
monitor_echo = yes
build_flags =
;   -D ELOG_SD_ENABLE
;   -D ELOG_SPIFFS_ENABLE
    -D ELOG_SYSLOG_ENABLE
    -D ELOG_TIMER_ENABLE
lib_deps = 
	adafruit/Adafruit TCA8418
	hideakitai/PCA95x5
	fastled/FastLED
	maxint-rd/TM16xx LEDs and Buttons
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ADS1X15
	x385832/Elog@^2.0.17