API Documentation: Panel Class Reference
Panel Class Reference
Public Member Functions
virtual int getStartIndex () const
Gets the start index of this panel on the LED strip.
virtual int getLedCount () const
Gets the number of LEDs in this panel.
virtual const Led * getLedTable () const
Gets the LED table for this panel.
virtual CRGB * getLedStrip () const
Gets the LED strip for this panel.
Protected Member Functions
Panel ()
Protected constructor to prevent direct instantiation.
void setInstrLights (uint16_t newValue, const CRGB &color=NVIS_GREEN_A)
Set the color of all instrument backlight LEDs.
void setConsoleLights (uint16_t newValue, const CRGB &color=NVIS_GREEN_A)
Sets the color of all console backlight LEDs.
void setIndicatorColor (LedRole role, const CRGB &color)
Sets the color of LEDs with a specific role.
void setFloodlights (uint16_t newValue)
Sets the brightness of floodlight LEDs.
void setAllLightsOff ()
Turns off all lights in this panel, irrespective of their role, and resets brightness state.
Protected Attributes
int panelStartIndex
int ledCount
const Led * ledTable
CRGB * ledStrip
uint16_t current_backl_brightness
uint16_t current_console_brightness
uint16_t current_flood_brightness
Panel * nextPanel
Friends
class Channel
Detailed Description
Definition at line 41 of file Panel.h.
Constructor & Destructor Documentation
Panel()
Panel::Panel () inline protected
Protected constructor to prevent direct instantiation.
See also
This method is called by derived panel classes
Definition at line 75 of file Panel.h.
            {
        current_backl_brightness = 0;
        current_console_brightness = 0;
        current_flood_brightness = 0;
        nextPanel = nullptr;  // Initialize next panel pointer
    }
Member Function Documentation
getStartIndex()
virtual int Panel::getStartIndex () const inline virtual
Gets the start index of this panel on the LED strip.
Returns
The start index
Definition at line 47 of file Panel.h.
{ return panelStartIndex; }
Referenced by setAllLightsOff(), setConsoleLights(), setFloodlights(), setIndicatorColor(), and setInstrLights().
getLedCount()
virtual int Panel::getLedCount () const inline virtual
Gets the number of LEDs in this panel.
Returns
The LED count
Reimplemented in LdgGearPanel, and SelectJettPanel.
Definition at line 53 of file Panel.h.
{ return ledCount; }
Referenced by setAllLightsOff(), setConsoleLights(), setFloodlights(), setIndicatorColor(), and setInstrLights().
getLedTable()
virtual const Led * Panel::getLedTable () const inline virtual
Gets the LED table for this panel.
Returns
Pointer to the LED table
Reimplemented in LdgGearPanel, and SelectJettPanel.
Definition at line 59 of file Panel.h.
{ return ledTable; }
Referenced by setAllLightsOff(), setConsoleLights(), setFloodlights(), setIndicatorColor(), and setInstrLights().
getLedStrip()
virtual CRGB * Panel::getLedStrip () const inline virtual
Gets the LED strip for this panel.
Returns
Pointer to the LED strip
Definition at line 65 of file Panel.h.
{ return ledStrip; }
Referenced by setAllLightsOff(), setConsoleLights(), setFloodlights(), setIndicatorColor(), and setInstrLights().
setInstrLights()
void Panel::setInstrLights (uint16_t newValue, const CRGB & color = NVIS_GREEN_A) inline protected
Set the color of all instrument backlight LEDs.
Parameters
newValue The new brightness value (0-65535)
color The color to set (defaults to NVIS_GREEN_A)
See also
This method is called by Channel::updateInstrLights()
Definition at line 99 of file Panel.h.
{
        if (!getLedStrip() || !getLedTable()) return;                 // Safety checks
        if (newValue == current_backl_brightness) return;             // Exit if no brightness change
        int scale = map(newValue, 0, 65535, 0, 255);                  // Map the brightness scale factor to a range of 0-255
        CRGB target = color;
        target.nscale8_video(scale);                                  // Use FastLED's nscale8_video to apply the scale factor
        CRGB target2 = NVIS_CGRB_GREEN_A;                             // For GRB LEDs (e.g. Radar Altimeter and Standby Instruments)
        target2.nscale8_video(scale);
        current_backl_brightness = newValue;                          // Update and save the current brightness value
        int n = getLedCount();
        for (int i = 0; i < n; i++) {                                 // For each LED, read info from PROGMEM; if LED is BACKLIGHT, set color
            Led led;
            memcpy_P(&led, &getLedTable()[i], sizeof(Led));           // getLedTable() accesses the panel's LED table
            uint16_t ledIndex = led.index + getStartIndex();
            if (led.role == LED_INSTR_BL) {
                getLedStrip()[ledIndex] = target;
            }
            if (led.role == LED_INSTR_BL_CGRB) {
                getLedStrip()[ledIndex] = target2;
            }
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);           // Inform that LEDs need to be updated
    }
References LedUpdateState::getInstance(), getLedCount(), getLedStrip(), getLedTable(), getStartIndex(), and LedUpdateState::setUpdateFlag().
Referenced by Channel::updateInstrLights().
setConsoleLights()
void Panel::setConsoleLights (uint16_t newValue, const CRGB & color = NVIS_GREEN_A) inline protected
Sets the color of all console backlight LEDs.
Parameters
newValue The new brightness value (0-65535)
color The color to set (defaults to NVIS_GREEN_A)
See also
This method is called by Channel::updateConsoleLights()
Definition at line 130 of file Panel.h.
                                                                               {                        // Set the color of all LEDs with role LED_CONSOLE_BL
        if (!getLedStrip() || !getLedTable()) return;                 // Safety checks
        if (newValue == current_console_brightness) return;           // Exit if no brightness change
        int scale = map(newValue, 0, 65535, 0, 255);                  // Map the brightness scale factor to a range of 0-255
        CRGB target = color;
        target.nscale8_video(scale);                                  // Use FastLED's nscale8_video to apply the scale factor
        current_console_brightness = newValue;                        // Update and save the current brightness value
        int n = getLedCount();
        for (int i = 0; i < n; i++) {                                 // For each LED, read info from PROGMEM; if LED is BACKLIGHT, set color
            Led led;
            memcpy_P(&led, &getLedTable()[i], sizeof(Led));           // getLedTable() accesses the panel's LED table
            uint16_t ledIndex = led.index + getStartIndex();
            if (led.role == LED_CONSOLE_BL) {
                getLedStrip()[ledIndex] = target;
            }
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);           // Inform that LEDs need to be updated
    }
References LedUpdateState::getInstance(), getLedCount(), getLedStrip(), getLedTable(), getStartIndex(), and LedUpdateState::setUpdateFlag().
Referenced by Channel::updateConsoleLights().
setIndicatorColor()
void Panel::setIndicatorColor (LedRole role, const CRGB & color) inline protected
Sets the color of LEDs with a specific role.
Parameters
role The role of LEDs to update
color The color to set
See also
This method is called by derived panel classes to update indicator lights
Definition at line 156 of file Panel.h.
                                                            {         // Set color of specific LEDs ("role" parameter)
        if (!getLedStrip() || !getLedTable()) return;
        int n = getLedCount();
        for (int i = 0; i < n; i++) {
            Led led;
            memcpy_P(&led, &getLedTable()[i], sizeof(Led));
            uint16_t ledIndex = led.index + getStartIndex();
            if (led.role == role) {
                getLedStrip()[ledIndex] = color;
            }
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);           // Inform that LEDs need to be updated
    }
References LedUpdateState::getInstance(), getLedCount(), getLedStrip(), getLedTable(), getStartIndex(), and LedUpdateState::setUpdateFlag().
setFloodlights()
void Panel::setFloodlights (uint16_t newValue) inline protected
Sets the brightness of floodlight LEDs.
Parameters
newValue The new brightness value (0-65535)
See also
This method is called by Channel::updateFloodLights()
Definition at line 175 of file Panel.h.
                                           {                          // Set the brightness of LEDs with role LED_FLOOD
        if (!getLedStrip() || !getLedTable()) return;                 // Same structure as setInstrLights()
        if (newValue == current_flood_brightness) return;
        current_flood_brightness = newValue;
        uint8_t scale = map(newValue, 0, 65535, 0, 255);
        CRGB target = NVIS_WHITE;
        target.nscale8_video(scale);
        int n = getLedCount();
        for (int i = 0; i < n; i++) {
            Led led;
            memcpy_P(&led, &getLedTable()[i], sizeof(Led));
            uint16_t ledIndex = led.index + getStartIndex();
            if (led.role == LED_FLOOD) {
                getLedStrip()[ledIndex] = target;
            }
        }
        LedUpdateState::getInstance()->setUpdateFlag(true);           // Inform that LEDs need to be updated
    }
References LedUpdateState::getInstance(), getLedCount(), getLedStrip(), getLedTable(), getStartIndex(), and LedUpdateState::setUpdateFlag().
Referenced by Channel::updateFloodLights().
setAllLightsOff()
void Panel::setAllLightsOff () inline protected
Turns off all lights in this panel, irrespective of their role, and resets brightness state.
See also
This method is called by Channel::setAllLightsOff()
Definition at line 201 of file Panel.h.
                           {                                          // Turn off all lights and reset brightness state
        if (!getLedStrip() || !getLedTable()) return;                 // Safety checks
        CRGB* ledArray = getLedStrip();
        int startIndex = getStartIndex();
        int panelLedCount = getLedCount();
        for (int i = 0; i < panelLedCount; i++) {
            ledArray[startIndex + i] = NVIS_BLACK;
        }
        // Reset all brightness variables to 0
        current_backl_brightness = 0;
        current_console_brightness = 0;
        current_flood_brightness = 0;
        LedUpdateState::getInstance()->setUpdateFlag(true);           // Inform that LEDs need to be updated
    }
References LedUpdateState::getInstance(), getLedCount(), getLedStrip(), getLedTable(), getStartIndex(), and LedUpdateState::setUpdateFlag().
Referenced by Channel::setAllLightsOff().
Friends And Related Symbol Documentation
Channel
friend class Channel friend
Definition at line 68 of file Panel.h.
Member Data Documentation
panelStartIndex
int Panel::panelStartIndex protected
Definition at line 83 of file Panel.h.
ledCount
int Panel::ledCount protected
Definition at line 84 of file Panel.h.
ledTable
const Led* Panel::ledTable protected
Definition at line 85 of file Panel.h.
ledStrip
CRGB* Panel::ledStrip protected
Definition at line 86 of file Panel.h.
current_backl_brightness
uint16_t Panel::current_backl_brightness protected
Definition at line 87 of file Panel.h.
current_console_brightness
uint16_t Panel::current_console_brightness protected
Definition at line 88 of file Panel.h.
current_flood_brightness
uint16_t Panel::current_flood_brightness protected
Definition at line 89 of file Panel.h.
nextPanel
Panel* Panel::nextPanel protected
Definition at line 90 of file Panel.h.
The documentation for this class was generated from the following file:
/github/workspace/embedded/OH2_Lower_Instrument_Panel/2A13-BACKLIGHT_CONTROLLER/helpers/Panel.h