# Any extra libraries included by this sketch (space separated)
LIBRARIES = Adafruit_NeoPixel Servo dcs-bios-arduino-library

# Uncomment one of the following to choose the target board
# include ../../include/mega2560.mk
include ../../include/promicro.mk
# include ../../include/promini.mk
# include ../../include/s2mini.mk
