API Documentation: Channel Class Reference
Channel Class Reference
Public Member Functions
Channel (uint8_t p, const char *pcb, CRGB *ledArray, uint16_t count)
Constructor for the Channel class.
void initialize ()
Initializes the LED strip with FastLED.
template<typename PanelType >
void addPanel ()
Adds a panel to the channel's linked list.
uint8_t getPin () const
Gets the pin number for this channel.
const char * getPcbName () const
Gets the PCB name for this channel.
uint16_t getLedCount () const
Gets the number of LEDs in this channel.
CRGB * getLeds () const
Gets the LED array for this channel.
Panel * getFirstPanel () const
Gets the first panel in the channel's linked list.
uint8_t getPanelCount () const
Gets the number of panels in this channel.
void updateInstrLights (uint16_t brightness, const CRGB &color=NVIS_GREEN_A)
Updates backlights for all panels in this channel.
void updateConsoleLights (uint16_t brightness, const CRGB &color=NVIS_GREEN_A)
Updates console lights for all panels in this channel.
void updateFloodLights (uint16_t brightness)
Updates flood lights for all panels in this channel.
void setAllLightsOff ()
Turns off all lights in all panels of this channel and resets brightness state.
Detailed Description
Definition at line 35 of file Channel.h.
Constructor & Destructor Documentation
Channel()
Channel::Channel (uint8_t p, const char * pcb, CRGB * ledArray, uint16_t count) inline
Constructor for the Channel class.
Parameters
p Pin number for the LED strip
pcb Name of the PCB this channel is connected to
ledArray Pointer to the LED array
count Number of LEDs in the strip
Definition at line 54 of file Channel.h.
{
        pin = p;
        pcbName = pcb;
        leds = ledArray;   // Store pointer to the static array
        ledCount = count;
        currentIndex = 0;  // Initialize currentIndex to 0
        firstPanel = nullptr;  // Initialize first panel pointer
        panelCount = 0;    // Initialize panel count
    }
Member Function Documentation
initialize()
void Channel::initialize () inline
Initializes the LED strip with FastLED.
See also
This method is called during setup in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 68 of file Channel.h.
                      {
        // Use a switch statement to overcome strange behaviour of FastLED to have a pin number at compile time
        switch(pin) {
            case 4:  FastLED.addLeds<WS2812B, 4, GRB>(leds, ledCount); break;
            case 5:  FastLED.addLeds<WS2812B, 5, GRB>(leds, ledCount); break;
            case 6:  FastLED.addLeds<WS2812B, 6, GRB>(leds, ledCount); break;
            case 7:  FastLED.addLeds<WS2812B, 7, GRB>(leds, ledCount); break;
            case 8:  FastLED.addLeds<WS2812B, 8, GRB>(leds, ledCount); break;
            case 9:  FastLED.addLeds<WS2812B, 9, GRB>(leds, ledCount); break;
            case 10: FastLED.addLeds<WS2812B, 10, GRB>(leds, ledCount); break;
            case 11: FastLED.addLeds<WS2812B, 11, GRB>(leds, ledCount); break;
            case 12: FastLED.addLeds<WS2812B, 12, GRB>(leds, ledCount); break;
            case 13: FastLED.addLeds<WS2812B, 13, GRB>(leds, ledCount); break;
            default: break; // Handle invalid pin
        }
        fill_solid(leds, ledCount, NVIS_BLACK);
    }
addPanel()
template<typename PanelType > void Channel::addPanel () inline
Adds a panel to the channel's linked list.
Template Parameters
PanelType The type of panel to add
See also
This method is called by setup() in 2A13-BACKLIGHT_CONTROLLER.ino
Definition at line 93 of file Channel.h.
                    {
        PanelType* panel = PanelType::getInstance(currentIndex, leds);
        // Safety check: Ensure we don't exceed the channel's LED capacity
        if (currentIndex + panel->getLedCount() > ledCount) {
            // Halt execution and indicate error with LED pattern
            while(1) {
                digitalWrite(LED_BUILTIN, HIGH);
                delay(100);
                digitalWrite(LED_BUILTIN, LOW);
                delay(100);
            }
        }
        // Add panel to linked list
        if (firstPanel == nullptr) {
            firstPanel = panel;  // First panel in the channel
        } else {
            // Find the last panel
            Panel* currentPanel = firstPanel;
            while (currentPanel->nextPanel != nullptr) {
                currentPanel = currentPanel->nextPanel;
            }
            currentPanel->nextPanel = panel;  // Add new panel at the end
        }
        panelCount++;
        currentIndex += panel->getLedCount();
    }
getPin()
uint8_t Channel::getPin () const inline
Gets the pin number for this channel.
Returns
The pin number
Definition at line 128 of file Channel.h.
{ return pin; }
getPcbName()
const char * Channel::getPcbName () const inline
Gets the PCB name for this channel.
Returns
The PCB name
Definition at line 134 of file Channel.h.
{ return pcbName; }
getLedCount()
uint16_t Channel::getLedCount () const inline
Gets the number of LEDs in this channel.
Returns
The LED count
Definition at line 140 of file Channel.h.
{ return ledCount; }
getLeds()
CRGB * Channel::getLeds () const inline
Gets the LED array for this channel.
Returns
Pointer to the LED array
Definition at line 146 of file Channel.h.
{ return leds; }
getFirstPanel()
Panel * Channel::getFirstPanel () const inline
Gets the first panel in the channel's linked list.
Returns
Pointer to the first panel
Definition at line 152 of file Channel.h.
{ return firstPanel; }
getPanelCount()
uint8_t Channel::getPanelCount () const inline
Gets the number of panels in this channel.
Returns
The panel count
Definition at line 158 of file Channel.h.
{ return panelCount; }
updateInstrLights()
void Channel::updateInstrLights (uint16_t brightness, const CRGB & color = NVIS_GREEN_A) inline
Updates backlights for all panels in this channel.
Parameters
brightness The brightness value to set
color The color to set (defaults to NVIS_GREEN_A)
See also
This method is called by Board::fillSolid() and Board::updateInstrumentLights()
Definition at line 166 of file Channel.h.
{
        Panel* current = firstPanel;
        while (current != nullptr) {
            current->setInstrLights(brightness, color);
            current = current->nextPanel;
        }
    }
References Panel::setInstrLights().
Referenced by Board::fillSolid(), Board::processMode(), and Board::updateInstrumentLights().
updateConsoleLights()
void Channel::updateConsoleLights (uint16_t brightness, const CRGB & color = NVIS_GREEN_A) inline
Updates console lights for all panels in this channel.
Parameters
brightness The brightness value to set
color The color to set (defaults to NVIS_GREEN_A)
See also
This method is called by Board::updateConsoleLights()
Definition at line 180 of file Channel.h.
{
        Panel* current = firstPanel;
        while (current != nullptr) {
            current->setConsoleLights(brightness, color);
            current = current->nextPanel;
        }
    }
References Panel::setConsoleLights().
Referenced by Board::fillSolid(), Board::processMode(), and Board::updateConsoleLights().
updateFloodLights()
void Channel::updateFloodLights (uint16_t brightness) inline
Updates flood lights for all panels in this channel.
Parameters
brightness The brightness value to set
See also
This method is called by Board::updateFloodLights()
Definition at line 193 of file Channel.h.
{
        Panel* current = firstPanel;
        while (current != nullptr) {
            current->setFloodlights(brightness);
            current = current->nextPanel;
        }
    }
References Panel::setFloodlights().
Referenced by Board::processMode(), and Board::updateFloodLights().
setAllLightsOff()
void Channel::setAllLightsOff () inline
Turns off all lights in all panels of this channel and resets brightness state.
See also
This method is called by Board::setAllLightsOff()
Definition at line 205 of file Channel.h.
{
        // Clear all LEDs in the entire channel array (not just panel-tracked ones)
        fill_solid(leds, ledCount, NVIS_BLACK);
        // Also clear panel-tracked LEDs and reset brightness state
        Panel* current = firstPanel;
        while (current != nullptr) {
            current->setAllLightsOff();
            current = current->nextPanel;
        }
    }
References Panel::setAllLightsOff().
Referenced by Board::setAllLightsOff().
The documentation for this class was generated from the following file:
/github/workspace/embedded/OH2_Lower_Instrument_Panel/2A13-BACKLIGHT_CONTROLLER/helpers/Channel.h