# The target Arduino board for this sketch.  Run `make show_boards` to see a list.
BOARD_TAG  = promicro
# The target processor for this board.  Run `make show_submenu` to see a list.
BOARD_SUB  = 16MHzatmega32U4
# Any extra libraries included by this sketch (space separated)
ARDUINO_LIBS = Adafruit_NeoPixel Servo dcs-bios-arduino-library

include ../../include/promicro.mk
include ../../include/openhornet.mk
